config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"



  get "flats/search", to: "flats#search"

  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to @flat, notice: "Flat info successfully edited"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy!
    redirect_to flats_url, notice: "Flat was successfully deleted."
  end

  def search
    @searchterm = params[:search]
    @flats = Flat.where("name LIKE '%#{@searchterm}%' ")
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f|%>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests%>
  <%= f.input :image%>
  <%= f.submit %>
<% end %>

app/views/flats/edit.html.erb
<h1> Edit <%= @flat.name %> </h1>

<%= render "form", flat: @flat%>

<br>
<%= link_to "Index", flats_path%>

app/views/flats/index.html.erb
<%= link_to "Add your flat", new_flat_path %>

<p> Showing all <%= @flats.count %> flats. </p>

<% @flats.each do |flat| %>
<div class="index-card"> <strong> <%= flat.name %> </strong>
 <p> <%= flat.address %> </p>
 <p> <% if flat.image.present? %> <%= image_tag flat.image, size: "128x96", alt: "Flat Image" %> <%end%> </p>
 <p> <%= flat.number_of_guests %> guests -
 $<%= flat.price_per_night %> </p>
  <p> <%= link_to "More info", flat_path(flat) %> - <%= link_to "Edit", edit_flat_path(flat) %> - <%= link_to "Delete", flat_path(flat), data: { turbo_method: :delete} %> </p>
</div>
<% end %>

app/views/flats/new.html.erb
<h1> Add New Flat </h1>

<%= render "form", flat: @flat%>

<br>
<%= link_to "Index", flats_path%>

app/views/flats/search.html.erb
<%= link_to "Add your flat", new_flat_path %>

<h1> Search results for "<%=@searchterm%>"" </h1>

<p> Showing all <%= @flats.count %> flats. </p>

<%= form_with url: "search", method: :get do |f| %>
<%= f.label :search, "Search again:" %>
<%= f.search_field :search %>
<%= f.submit "search" %>
<% end %>

<% @flats.each do |flat| %>
<div class="index-card"> <strong> <%= flat.name %> </strong>
 <p> <%= flat.address %> </p>
 <p> <% if flat.image.present? %> <%= image_tag flat.image, size: "128x96", alt: "Flat Image" %> <%end%> </p>
 <p> <%= flat.number_of_guests %> guests -
 $<%= flat.price_per_night %> </p>
  <p> <%= link_to "More info", flat_path(flat) %> - <%= link_to "Edit", edit_flat_path(flat) %> - <%= link_to "Delete", flat_path(flat), data: { turbo_method: :delete} %> </p>
</div>
<% end %>

<%= link_to "Back to main page", flats_path%>

app/views/flats/show.html.erb
<h1> <%= @flat.name %> </h1>

<p> <%= @flat.address %> </p>

<p>
<%= image_tag @flat.image, size: "256x128", alt: "Flat Image" %>
</p>

<p> <%= @flat.description %> </p>

<h2> Details </h2>
<p> <%= @flat.number_of_guests %> guests max </p>
<p> $<%= @flat.price_per_night %> / night </p>

<div class="book">
  <h3> Book this place! </h3>
  <p> From: </p>
  <p> To: </p>
  <button> Book </button>
</div>

<p>
<%= link_to "Edit", edit_flat_path(@flat) %>  -
<%= link_to "Delete", flat_path(@flat), data: { turbo_method: :delete} %>  -

<%= link_to "Back to main page", flats_path%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <div class="top-banner">
    <h1> <%= link_to "Simple Flat Rentals", flats_path, style: "text-decoration: none; color: black;" %> </h1>
  </div>

  <div class="main">
    <%= yield %>
  </div>
  </body>
</html>